#!/usr/bin/env python3
"""Sync semantic view YAML into a dbt macro payload.

This script is intended to be used from pre-commit and CI across data-product repos.
"""

from __future__ import annotations

import argparse
import pathlib
import sys


HEADER_TEMPLATE = """{#
  Auto-generated by dbt-snow-cortex semantic view sync.
    Source of truth: __SOURCE_PATH__
  Do not edit this file directly.
#}
"""


def normalize_text(text: str) -> str:
    """Normalize line endings and ensure exactly one trailing newline."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return text.rstrip("\n") + "\n"


def build_macro(yaml_text: str, macro_name: str, source_path: str) -> str:
    """Render the target SQL macro containing the YAML payload in a raw block."""
    normalized_yaml = normalize_text(yaml_text).rstrip("\n")

    # Preserve raw-block integrity if YAML contains a Jinja raw terminator token.
    normalized_yaml = normalized_yaml.replace("{% endraw %}", "{% endraw %}{% raw %}")

    header = HEADER_TEMPLATE.replace("__SOURCE_PATH__", source_path)
    body = (
        "{% macro " + macro_name + "() %}\n"
        "{% raw %}" + normalized_yaml + "\n"
        "{% endraw %}\n"
        "{% endmacro %}\n"
    )
    return normalize_text(header + body)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or validate semantic-view YAML macro from source YAML."
    )
    parser.add_argument(
        "--yaml-path",
        required=True,
        help="Path to source semantic YAML file.",
    )
    parser.add_argument(
        "--macro-path",
        required=True,
        help="Path to generated macro SQL file.",
    )
    parser.add_argument(
        "--macro-name",
        required=True,
        help="Macro function name to generate.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validation-only mode. Exit non-zero if macro content is out of sync.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    yaml_path = pathlib.Path(args.yaml_path)
    macro_path = pathlib.Path(args.macro_path)

    if not yaml_path.exists():
        print(f"[semantic-view-sync] Source YAML not found: {yaml_path}", file=sys.stderr)
        return 2

    source_yaml = yaml_path.read_text(encoding="utf-8")
    generated_macro = build_macro(
        yaml_text=source_yaml,
        macro_name=args.macro_name,
        source_path=args.yaml_path,
    )

    existing_macro = ""
    if macro_path.exists():
        existing_macro = normalize_text(macro_path.read_text(encoding="utf-8"))

    if args.check:
        if existing_macro != generated_macro:
            print(
                "[semantic-view-sync] Drift detected between YAML and generated macro:\n"
                f"  YAML : {yaml_path}\n"
                f"  Macro: {macro_path}\n"
                "Run the hook without --check to regenerate.",
                file=sys.stderr,
            )
            return 1

        print(f"[semantic-view-sync] OK: {macro_path} is in sync with {yaml_path}")
        return 0

    if existing_macro != generated_macro:
        macro_path.parent.mkdir(parents=True, exist_ok=True)
        macro_path.write_text(generated_macro, encoding="utf-8")
        print(f"[semantic-view-sync] Updated {macro_path} from {yaml_path}")
        return 0

    print(f"[semantic-view-sync] No changes needed for {macro_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
